[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.33.0"
packages = ["rpx"]
ci = "github"
installers = ["shell", "powershell"]
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
install-path = "CARGO_HOME"
hosting = ["simple", "github"]
simple-download-url = "https://rrepo.org/rpx/{tag}"
host-jobs = ["./upload-r2"]
install-updater = false

[dist.azure-windows-sign]
endpoint = "https://weu.codesigning.azure.net/"
account-name = "rpx-signing-account"
certificate-profile-name = "rpx-public-trust"
